name: zzzbookly
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^14.8.0
  url_launcher: ^6.3.1
  sliver_tools: ^0.2.12
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/icon/

  fonts:
    - family: KeplerStd
      fonts:
        - asset: assets/fonts/kepler/KeplerStdLight.otf
          weight: 300
        - asset: assets/fonts/kepler/KeplerStdRegular.otf
          weight: 400
        - asset: assets/fonts/kepler/KeplerStdMedium.otf
          weight: 500
        - asset: assets/fonts/kepler/KeplerStdSemibold.otf
          weight: 600
        - asset: assets/fonts/kepler/KeplerStdBold.otf
          weight: 700
        - asset: assets/fonts/kepler/KeplerStdBlack.otf
          weight: 900
